CC = gcc
LD = gcc

CFLAGS = -g3 -Wall -fmessage-length=0
LDFLAGS =

# Put verbosity on
ifeq ($(V),1)
	VERBOSE	=
else
	VERBOSE = @
endif


main: main.o

# Launch the program
launch: all
	$(VERBOSE) ./$(EXEC)

l: launch

# Debug the program
debug: all
	$(VERBOSE) gdb $(EXEC)

# Launch DoxyWizard
doxy: $(SRC)
	$(VERBOSE) doxygen Doxyfile

# Delete documentation generated by Doxygen
rmdoxy:
	$(VERBOSE) rm -R doxygen/latex
	$(VERBOSE) rm -R doxygen/html

# Indent the files
indent: $(SRC) $(HDR)
	$(VERBOSE) indent \
	--blank-lines-after-declarations \
	--blank-lines-after-procedures \
	--blank-lines-before-block-comments \
	--no-blank-lines-after-commas \
	--braces-on-if-line \
	--braces-on-func-def-line \
	--braces-on-struct-decl-line \
	--case-indentation0 \
	--case-brace-indentation4 \
	--cuddle-do-while \
	--declaration-indentation16 \
	--dont-break-function-decl-args \
	--dont-break-function-decl-args-end \
	--dont-break-procedure-type \
	--dont-format-comments \
	--dont-format-first-column-comments \
	--dont-cuddle-else \
	--remove-preprocessor-space \
	--space-after-cast \
	--space-after-for \
	--space-after-if \
	--space-after-parentheses \
	--no-space-after-function-call-names \
	--space-after-while \
	--indent-level4 \
	$(SRC) $(HDR)
	$(VERBOSE) rm `find . -name *~`
